name: Docker Image

on:
  push:
    paths-ignore:
      - ".gitlab-ci.yml"
    pull_request:

jobs:

  dist:
    name: Build Distributions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ./docker.sh release
      - run: ./docker.sh release-windows
      - run: ./docker.sh release-macos
      - uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist

  build:
    name: Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Docker Image
        run: docker build --tag jasonish/evebox:master .
      - name: Push Docker image to hub.docker.com (only for master)
        if: github.ref == 'refs/heads/master'
        run: |
          echo ${{secrets.DOCKER_HUB_TOKEN}} | \
              docker login -u ${{secrets.DOCKER_HUB_USERNAME}} --password-stdin
          docker push jasonish/evebox:master
